version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: dain-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/data:/app/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: dain-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "4173:4173"
    command: npm run preview -- --host 0.0.0.0 --port 4173
