services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dain-backend
    env_file:
      - .env
    volumes:
      - ./backend/app/data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dain-frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    command: npm run preview -- --host 0.0.0.0 --port 4173
    networks:
      - default

networks:
  default:
    driver: bridge